/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Badge: typeof import('./src/components/ui/badge').Badge
  const Button: typeof import('./src/components/ui/button').Button
  const Card: typeof import('./src/components/ui/card').Card
  const Dialog: typeof import('./src/components/ui/dialog').Dialog
  const DialogClose: typeof import('./src/components/ui/dialog').DialogClose
  const DialogContent: typeof import('./src/components/ui/dialog').DialogContent
  const DialogDescription: typeof import('./src/components/ui/dialog').DialogDescription
  const DialogFooter: typeof import('./src/components/ui/dialog').DialogFooter
  const DialogHeader: typeof import('./src/components/ui/dialog').DialogHeader
  const DialogOverlay: typeof import('./src/components/ui/dialog').DialogOverlay
  const DialogPortal: typeof import('./src/components/ui/dialog').DialogPortal
  const DialogTitle: typeof import('./src/components/ui/dialog').DialogTitle
  const DialogTrigger: typeof import('./src/components/ui/dialog').DialogTrigger
  const FormField: typeof import('./src/components/ui/form-field').FormField
  const Fragment: typeof import('react').Fragment
  const Input: typeof import('./src/components/ui/input').Input
  const Link: typeof import('@tanstack/react-router').Link
  const Outlet: typeof import('@tanstack/react-router').Outlet
  const Suspense: typeof import('react').Suspense
  const badgeVariants: typeof import('./src/components/ui/badge').badgeVariants
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cn: typeof import('./src/utils/cn').cn
  const create: typeof import('zustand').create
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const formatDate: typeof import('./src/utils/date-format').formatDate
  const forwardRef: typeof import('react').forwardRef
  const fromNow: typeof import('./src/utils/date-format').fromNow
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const redirect: typeof import('@tanstack/react-router').redirect
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAppVersion: typeof import('./src/hooks/useAppVersion').useAppVersion
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLoaderData: typeof import('@tanstack/react-router').useLoaderData
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('@tanstack/react-router').useNavigate
  const useOptimistic: typeof import('react').useOptimistic
  const useParams: typeof import('@tanstack/react-router').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRouter: typeof import('@tanstack/react-router').useRouter
  const useRouterState: typeof import('@tanstack/react-router').useRouterState
  const useSearch: typeof import('@tanstack/react-router').useSearch
  const useSocketEvent: typeof import('./src/hooks/useSocketIO').useSocketEvent
  const useSocketIO: typeof import('./src/hooks/useSocketIO').useSocketIO
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const useTranslation: typeof import('react-i18next').useTranslation
}
// for type re-export
declare global {
  // @ts-ignore
  export type { BadgeVariants } from './src/components/ui/badge'
  import('./src/components/ui/badge')
  // @ts-ignore
  export type { ButtonVariant, ButtonShape, ButtonSize } from './src/components/ui/button'
  import('./src/components/ui/button')
}
