import { queryClient } from "./providers/query-client-provider";
import { routeTree } from "./routeTree.gen";
import { createRouter } from "@tanstack/react-router";

/**
 * TanStack Router instance. The routeTree is auto-generated by the Vite plugin
 * from the file-based routes under src/routes/. The QueryClient is injected into
 * router context so routes can prefetch queries in loaders.
 */
export const router = createRouter({
  routeTree,
  context: { queryClient },
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
